version: "3"

services:
  postgres:
    env_file:
      - postgres.env
    image: postgres:16
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - pgpadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
